version: "3.7"
services:
  postgres:
    image: postgres:10-alpine
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # api:
  #   build:
  #     context: ./movie-api
  #   env_file: .env
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - postgres
volumes:
  postgres:
